### ISSUE TITLE
Simply adding Forgix causes build to fail

### ISSUE THREAD

**Issue by wafflecoffee** [PacifistMC/Forgix#8]
https://streamable.com/39b4e7
Repo - https://github.com/emmods/emcutils

**Comment by Ran-helo** [comment]
Just adding Forgix shouldn't mess with the builds? _maybe adding the plugin makes Gradle add more checks for some stuff?_
But for your issue it should be fixable by doing `remapJar.dependsOn(optimizeOutputsOfShadowJar)` for each of the projects

other than that I have no idea on why this happens _maybe am calling some function that messes with gradle on plugin initialization?_
Though if it happens on plugin initialization then something should be wrong at `ForgixExtension` class since the rest of the code only runs when `mergeJars` task is called

**Comment by Ran-helo** [comment]
Aight after lots testing
it seems adding the plugin makes Architectury check for an extra file which is the lwjgl library
Apparently in 1.19 they added a single file or so that requires Java 19

I don't know why it didn't throw this error for you earlier because for me this Java 19 error is on all of my Architectury mods that are on 1.19

[You can check out a temp hack on how to fix it here](https://discord.com/channels/792699517631594506/993160859524268133/993162229065207848)
[Note: For future people seeing this you will have to join the Architectury discord server](https://discord.gg/VgUJHVcfCs)

Anyways so basically the fix is that you have to open the lwjgl jar _the location of it should be given in the gradle logs_
using a zip manager and then you have to delete the "19" directory which is in the "META-INF/versions" directory

After fixing that, Forgix works on emcutils!
and the mods.toml and everything is processed and stuff so I guess issue #5 is about something going wrong
I'll close issue #5 for now but I'll reopen it after someone else encounters it again I guess

**Comment by Ran-helo** [comment]
This issue should now be fully fixed without requiring any user interaction
